import "./globals.css";
import Image from "next/image";
import styles from "./layout.module.css";
import utilStyles from "./utils.module.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App using App Router (",
  description: "Generated by create next app",
};

const name = "qaws7791";
export const siteTitle = "Next.js Sample Website using App Router";

export default function RootLayout({ children, home }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <header className={styles.header}>
            <Image
              priority
              src="/images/profile.jpg"
              className={utilStyles.borderCircle}
              height={144}
              width={144}
              alt=""
            />
            <h1 className={utilStyles.heading2Xl}>{name}</h1>
          </header>
          <main>{children}</main>
          {!home && (
            <div className={styles.backToHome}>
              <Link href="/">← Back to home</Link>
            </div>
          )}
        </div>
      </body>
    </html>
  );
}
