import './globals.css'
import Image from 'next/image'
import Link from 'next/link'
import './layout.css'

export const metadata = {
  title: 'Create Next App using App Router (',
  description: 'Generated by create next app',
}

const name = 'qaws7791'
export const siteTitle = 'Next.js Sample Website using App Router'

export default function RootLayout({children, home}) {
  return (
    <html lang="en">
      <body>
        <div>
          <header className="header">
            <div className="header-container">
              <h1 className="header__title">
                <a href="/">{name}</a>
              </h1>
              <div>
                <ul className="header__menu">
                  <li>
                    <a>Menu</a>
                  </li>
                  <li>
                    <a>Menu</a>
                  </li>
                  <li>
                    <a>Menu</a>
                  </li>
                  <li>
                    <a>Menu</a>
                  </li>
                </ul>
              </div>
            </div>
          </header>
          <main className="main">{children}</main>
          {!home && (
            <div>
              <Link href="/">← Back to home</Link>
            </div>
          )}
        </div>
      </body>
    </html>
  )
}
